name: puzzle
description: "A new Flutter project."

publish_to: "none" # Prevents accidental publishing to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  in_app_review: ^2.0.9
  flutter:
    sdk: flutter

  # Core dependencies
  cupertino_icons: ^1.0.6
  provider: ^6.1.2 # Adjusted to a compatible version
  flutter_svg: ^2.0.16
  google_fonts: ^6.2.1
  bordered_text: ^2.0.0
  dotted_line: ^3.2.2
  webview_flutter: ^4.9.0 # Resolvable version

  # Additional dependencies
  share_plus: ^10.1.2
  url_launcher: ^6.3.0
  package_info_plus: ^8.1.1
  http: ^1.2.2
  win32: ^5.9.0
  shared_preferences: ^2.3.3 # Resolvable version
  glass: ^2.0.0+2
  device_preview_plus: ^2.1.5
   #  unity_ads_plugin: ^0.3.22
  applovin_max: ^4.1.1
  change_app_package_name: ^1.4.0

  # Third-party or custom dependencies
  flutter_jigsaw_puzzle:
    git:
      url: https://github.com/mfagri/flutter_jigsaw_puzzle
  confetti: ^0.8.0
  blur: ^4.0.0
  google_mobile_ads: ^2.3.0
  facebook_audience_network:
     path: ./facebook_audience_network-1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

dependency_overrides:
  # For transitive dependencies, forcing compatible versions
  archive: ^3.6.1
  async: ^2.11.0
  characters: ^1.3.0
  clock: ^1.1.1
  collection: ^1.18.0
  image: ^3.3.0
  intl: ^0.19.0
  material_color_utilities: ^0.11.1
  meta: ^1.15.0
  path: ^1.9.0
  string_scanner: ^1.2.0
  webview_flutter_android: ^3.16.9

